// Mapa explícito de íconos de Lucide para categorías y ranuras (así el paquete incluye solo los usados).

import {
  Armchair,
  BatteryCharging,
  Box,
  Cable,
  CircuitBoard,
  Cpu,
  Disc3,
  Fan,
  Gamepad,
  Gamepad2,
  Gpu,
  HardDrive,
  Headphones,
  KeyRound,
  Keyboard,
  Laptop,
  MemoryStick,
  Monitor,
  MonitorSmartphone,
  Mouse,
  Package,
  PcCase,
  Plug,
  Router,
  Square,
  Webcam,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  Armchair,
  BatteryCharging,
  Box,
  Cable,
  CircuitBoard,
  Cpu,
  Disc3,
  Fan,
  Gamepad,
  Gamepad2,
  Gpu,
  HardDrive,
  Headphones,
  KeyRound,
  Keyboard,
  Laptop,
  MemoryStick,
  Monitor,
  MonitorSmartphone,
  Mouse,
  Package,
  PcCase,
  Plug,
  Router,
  Square,
  Webcam,
  Wrench,
  Zap,
};

/** Componente de ícono para un nombre de `Category.icon` / `BuildSlot.icon` (Package si no existe). */
export function categoryIcon(name: string): LucideIcon {
  return CATEGORY_ICONS[name] ?? Package;
}
